### PR TITLE
Update docker cpu tutorial

### PR DESCRIPTION
**Pull request by jonathanmv**
Describes more accurately how to run predictions locally, avoiding the creation of issues like the ones below:

https://github.com/idealo/image-super-resolution/issues/163
https://github.com/idealo/image-super-resolution/issues/166
https://github.com/idealo/image-super-resolution/issues/172
https://github.com/idealo/image-super-resolution/issues/175

### CODE REVIEW

**Review by cfrancesco — APPROVED** [review]
Long time coming, thanks

**Review by cfrancesco — APPROVED** [review]

**Review by cfrancesco — APPROVED** [review]

**Comment by jonathanmv** [comment]
> Long time coming, thanks

Super. Glad to help. I still can't merge the PR even though it's approved. Is there something else I need to do?

**Comment by cfrancesco** [comment]
> > Long time coming, thanks
> 
> Super. Glad to help. I still can't merge the PR even though it's approved. Is there something else I need to do?

No, you need permissions. As I left the company I also do not have them at the moment, I'm waiting for it and then I'll merge :)

**Comment by jonathanmv** [comment]
> > > Long time coming, thanks
> > 
> > 
> > Super. Glad to help. I still can't merge the PR even though it's approved. Is there something else I need to do?
> 
> No, you need permissions. As I left the company I also do not have them at the moment, I'm waiting for it and then I'll merge :)

That's great! Thank you

**Pull request merged**
