### PR TITLE
adding direct download weigths

### PR DESCRIPTION
**Pull request by jqueguiner**

### CODE REVIEW

**Comment by jqueguiner** [comment]
@cfrancesco

**Comment by cfrancesco** [comment]
Hi,
thank you very much, this could work.
It is however necessary for us to be able to manage the files that are available through those links.

**Comment by jqueguiner** [comment]
I can give you access to the bucket if you want I can even provide you a dedicated bucket

**Comment by datitran** [comment]
@jqueguiner Hi thanks this looks good and as @cfrancesco pointed out we would need access. You can send us the details to my mail datitran@gmail.com. By the way, can you please push to `dev`. Thanks

**Pull request closed without merging**
